//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<chiselsandbits:wrench_wood>);
recipes.remove(<magicbees:resource:11>);
recipes.remove(<minecraft:wheat_seeds> * 2);
recipes.remove(<tp:wooden_shears>);
//Don't touch me!
//#Add
recipes.addShaped(<storagedrawers:upgrade_creative>, [[<storagedrawers:upgrade_storage:4>, <minecraft:nether_star>, <storagedrawers:upgrade_storage:4>],[<minecraft:nether_star>, <storagedrawers:upgrade_template>, <minecraft:nether_star>], [<storagedrawers:upgrade_storage:4>, <minecraft:nether_star>, <storagedrawers:upgrade_storage:4>]]);
recipes.addShapedMirrored(<chiselsandbits:wrench_wood>, [[null, <minecraft:stick>, null],[null, <minecraft:stick>, <minecraft:stick>], [<minecraft:stick>, null, null]]);
recipes.addShaped(<woot:endershard>.withTag({wootMobNameKey: "minecraft:ender_dragon", wootMobDeaths: 64, wootMobDisplayName: "Ender Dragon", wootMobNameTag: ""}), [[<careerbees:ingredients:12>, <woot:endershard>, <careerbees:ingredients:11>],[<mysticalagradditions:insanium>, <draconicevolution:ender_energy_manipulator>, <mysticalagradditions:insanium>], [<simplyjetpacks:metaitemmods>, <draconicevolution:awakened_core>, <simplyjetpacks:metaitemmods>]]);
recipes.addShaped(<forestry:bee_princess_ge>.withTag({MaxH: 20, Mate: {Chromosomes: [{UID1: "morebees.species.rock", UID0: "morebees.species.rock", Slot: 0 as byte}, {UID1: "forestry.speedSlowest", UID0: "forestry.speedSlowest", Slot: 1 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 4 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 5 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 6 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 7 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 8 as byte}, {UID1: "morebees.flowersOre", UID0: "morebees.flowersOre", Slot: 9 as byte}, {UID1: "forestry.floweringSlowest", UID0: "forestry.floweringSlowest", Slot: 10 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 11 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 12 as byte}]}, Health: 20, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "morebees.species.rock", UID0: "morebees.species.rock", Slot: 0 as byte}, {UID1: "forestry.speedSlowest", UID0: "forestry.speedSlowest", Slot: 1 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 4 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 5 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 6 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 7 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 8 as byte}, {UID1: "morebees.flowersOre", UID0: "morebees.flowersOre", Slot: 9 as byte}, {UID1: "forestry.floweringSlowest", UID0: "forestry.floweringSlowest", Slot: 10 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 11 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 12 as byte}]}}), [[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>],[<minecraft:cobblestone>, <forestry:bee_princess_ge>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<forestry:bee_drone_ge>.withTag({MaxH: 20, Mate: {Chromosomes: [{UID1: "morebees.species.rock", UID0: "morebees.species.rock", Slot: 0 as byte}, {UID1: "forestry.speedSlowest", UID0: "forestry.speedSlowest", Slot: 1 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 4 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 5 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 6 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 7 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 8 as byte}, {UID1: "morebees.flowersOre", UID0: "morebees.flowersOre", Slot: 9 as byte}, {UID1: "forestry.floweringSlowest", UID0: "forestry.floweringSlowest", Slot: 10 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 11 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 12 as byte}]}, Health: 20, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "morebees.species.rock", UID0: "morebees.species.rock", Slot: 0 as byte}, {UID1: "forestry.speedSlowest", UID0: "forestry.speedSlowest", Slot: 1 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 4 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 5 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 6 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 7 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 8 as byte}, {UID1: "morebees.flowersOre", UID0: "morebees.flowersOre", Slot: 9 as byte}, {UID1: "forestry.floweringSlowest", UID0: "forestry.floweringSlowest", Slot: 10 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 11 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 12 as byte}]}}), [[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>],[<minecraft:cobblestone>, <forestry:bee_drone_ge>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShapeless(<minecraft:wheat_seeds>, [<minecraft:wheat>]);
recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "chickens:quartzchicken"}}), [[<minecraft:quartz>, <minecraft:quartz>, <minecraft:quartz>],[<minecraft:quartz>, <minecraft:egg>, <minecraft:quartz>], [<minecraft:quartz>, <minecraft:quartz>, <minecraft:quartz>]]);
recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "chickens:soulsandchicken"}}), [[<minecraft:soul_sand>, <minecraft:soul_sand>, <minecraft:soul_sand>],[<minecraft:soul_sand>, <minecraft:egg>, <minecraft:soul_sand>], [<minecraft:soul_sand>, <minecraft:soul_sand>, <minecraft:soul_sand>]]);
recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "chickens:sandchicken"}}), [[<minecraft:sand>, <minecraft:sand>, <minecraft:sand>],[<minecraft:sand>, <minecraft:egg>, <minecraft:sand>], [<minecraft:sand>, <minecraft:sand>, <minecraft:sand>]]);
recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "chickens:flintchicken"}}), [[<minecraft:flint>, <minecraft:flint>, <minecraft:flint>],[<minecraft:flint>, <minecraft:egg>, <minecraft:flint>], [<minecraft:flint>, <minecraft:flint>, <minecraft:flint>]]);
recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "chickens:logchicken"}}), [[<minecraft:log>, <minecraft:log>, <minecraft:log>],[<minecraft:log>, <minecraft:egg>, <minecraft:log>], [<minecraft:log>, <minecraft:log>, <minecraft:log>]]);
recipes.addShapedMirrored(<tp:wooden_shears>, [[<ore:plankWood>, null],[<minecraft:stick>, <ore:plankWood>]]);
furnace.addRecipe(<mysticalagriculture:crafting:5>, <minecraft:prismarine_shard>, 0.0);
//#Hide/Remove
// mods.jei.JEI.removeAndHide();
mods.jei.JEI.removeAndHide(<exnihilocreatio:block_end_cake>);
mods.jei.JEI.removeAndHide(<exnihilocreatio:item_material:1>);
mods.jei.JEI.removeAndHide(<extrautils2:teleporter:1>);
mods.jei.JEI.removeAndHide(<extrautils2:teleporter>);
mods.jei.JEI.removeAndHide(<skyresources:endportalcore>);
//File End
